allowBuilds:
  '@stellar/stellar-sdk': true
  '@swc/core': true
  blake-hash: true
  esbuild: true
  protobufjs: true
  sharp: true
  tiny-secp256k1: true
  usb: true
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - blake-hash
  - esbuild
  - protobufjs
  - sharp
  - tiny-secp256k1
  - usb
